version: "3.8"

services:
  wordpress:
    image: wordpress:php8.2-apache
    expose:
      - 80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - appnet

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  nuxt:
    build:
      context: ./nuxt-app
      dockerfile: Dockerfile
    volumes:
      - ./nuxt-app:/app
    ports:
      - "3000:3000" # наружу → 3000
    command: "npm run dev"
    networks:
      - appnet
    environment:
      NUXT_PUBLIC_API_BASE: "http://nuxt:3000"
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nuxt
      - wordpress
    networks:
      - appnet
volumes:
  wordpress_data:
  db_data:

networks:
  appnet:
